### ISSUE TITLE
Upgrade to ml-agents 0.9.3

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/obstacle-tower-source#7]
Is there a particular reason for supporting ml-agents v0.8.1?
Otherwise I'd just open up a PR for migrating to v0.9.3.

**Comment by awjuliani** [comment]
Hi @MarcoMeter ,

We are about to release ML-Agents v0.10, this fixes a compatibility issue with 2019.2. At that point we'd like to upgrade both versions (Which also involves updating the obstacle-tower-env repo and uploading new builds to GCS). If you want to update your PR once v0.10 is released, I'll be happy to test it and merge it in.

**Comment by MarcoMeter** [comment]
I just opened a new PR that updates to v0.10.0 and Unity v2019.2.8.

**Comment by MarcoMeter** [comment]
Hey @awjuliani 
Do you think updating ml-agents or Unity comes with performance gains concerning the simulation speed of Obstacle Tower?

**Comment by awjuliani** [comment]
Hi @MarcoMeter 

There may indeed be benefits from future versions of both. On the ML-Agents side there has been a fair amount of refactoring work which would likely lead to speed-ups. The rendering and physics on the Unity side are also always undergoing performance improvements each release, so there may be some benefit there as well. Unfortunately Obstacle Tower is currently in a maintenance state, rather than being actively developed. As such, I would be happy to take a look at PRs upgrading it, but can only devote time myself to active bugs.

**Comment by MarcoMeter** [comment]
On the first sight, the environment runs slower if built with Unity 2019.3.5f.

This runs 10 seconds slower given a PPO algorithm that utilizes 16 environment instances where 256 steps are sampled from each agent during training. (Tested on Windows).
